/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-12-07 17:50:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.wso2.carbon.identity.application.authentication.endpoint.util.Constants;
import org.owasp.encoder.Encode;

public final class oauth2_005fauthz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String loggedInUser = request.getParameter("loggedInUser");
    String scopeString = request.getParameter("scope");
    boolean displayScopes = Boolean.parseBoolean(getServletContext().getInitParameter("displayScopes"));

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>WSO2 Identity Server</title>\n");
      out.write("\n");
      out.write("    <link rel=\"icon\" href=\"images/favicon.png\" type=\"image/x-icon\"/>\n");
      out.write("    <link href=\"libs/bootstrap_3.3.5/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/Roboto.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/custom-common.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("    <script src=\"js/html5shiv.min.js\"></script>\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    function approved() {\n");
      out.write("        document.getElementById('consent').value = \"approve\";\n");
      out.write("        document.getElementById(\"oauth2_authz\").submit();\n");
      out.write("    }\n");
      out.write("    function approvedAlways() {\n");
      out.write("        document.getElementById('consent').value = \"approveAlways\";\n");
      out.write("        document.getElementById(\"oauth2_authz\").submit();\n");
      out.write("    }\n");
      out.write("    function deny() {\n");
      out.write("        document.getElementById('consent').value = \"deny\";\n");
      out.write("        document.getElementById(\"oauth2_authz\").submit();\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- header -->\n");
      out.write("<header class=\"header header-default\">\n");
      out.write("    <div class=\"container-fluid\"><br></div>\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"pull-left brand float-remove-xs text-center-xs\">\n");
      out.write("            <a href=\"#\">\n");
      out.write("                <img src=\"images/logo-inverse.svg\" alt=\"wso2\" title=\"wso2\" class=\"logo\">\n");
      out.write("                <h1><em>Identity Server</em></h1>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<!-- page content -->\n");
      out.write("<div class=\"container-fluid body-wrapper\">\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("\n");
      out.write("            <!-- content -->\n");
      out.write("            <div class=\"container col-xs-10 col-sm-6 col-md-6 col-lg-3 col-centered wr-content wr-login col-centered\">\n");
      out.write("                <div>\n");
      out.write("                    <h2\n");
      out.write("                            class=\"wr-title uppercase blue-bg padding-double white boarder-bottom-blue margin-none\">Authorize\n");
      out.write("                    </h2>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"boarder-all \">\n");
      out.write("                    <div class=\"clearfix\"></div>\n");
      out.write("                    <form action=\"../oauth2/authorize\" method=\"post\" id=\"oauth2_authz\" name=\"oauth2_authz\" class=\"form-horizontal\" >\n");
      out.write("                        <div class=\"padding-double login-form\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <p><strong>\n");
      out.write("                                    ");
      out.print(Encode.forHtml(request.getParameter("application")));
      out.write("\n");
      out.write("                                </strong> requests access to your profile information </p>\n");
      out.write("                                ");

                                    if (displayScopes && scopeString != null) {
                                
      out.write("\n");
      out.write("                                <ul>\n");
      out.write("                                ");

                                        String[] scopes = scopeString.split(" ");
                                        for (String scopeID : scopes) {

                                            if ("openid".equals(scopeID)) {
                                                continue;
                                            }
                                
      out.write("\n");
      out.write("                                        <li>");
      out.print(Encode.forHtml(scopeID));
      out.write("</li>\n");
      out.write("                                ");

                                        }
                                
      out.write("\n");
      out.write("                                </ul>\n");
      out.write("                                ");

                                    }
                                
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                    <table width=\"100%\" class=\"styledLeft\">\n");
      out.write("                        <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td class=\"buttonRow\" colspan=\"2\">\n");
      out.write("\n");
      out.write("                                <div style=\"text-align:left;\">\n");
      out.write("                                    <input type=\"button\" class=\"btn  btn-primary\" id=\"approve\" name=\"approve\"\n");
      out.write("                                           onclick=\"javascript: approved(); return false;\"\n");
      out.write("                                           value=\"Approve\"/>\n");
      out.write("                                    <input type=\"button\" class=\"btn\" id=\"chkApprovedAlways\"\n");
      out.write("                                           onclick=\"javascript: approvedAlways(); return false;\"\n");
      out.write("                                           value=\"Approve Always\"/>\n");
      out.write("                                    <input type=\"hidden\" id=\"hasApprovedAlways\" name=\"hasApprovedAlways\"\n");
      out.write("                                           value=\"false\"/>\n");
      out.write("                                    <input class=\"btn\" type=\"reset\" value=\"Deny\"\n");
      out.write("                                           onclick=\"javascript: deny(); return false;\"/>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print(Constants.SESSION_DATA_KEY_CONSENT);
      out.write("\"\n");
      out.write("                                       value=\"");
      out.print(Encode.forHtmlAttribute(request
                                   .getParameter(Constants.SESSION_DATA_KEY_CONSENT)));
      out.write("\"/>\n");
      out.write("                                <input type=\"hidden\" name=\"consent\" id=\"consent\"\n");
      out.write("                                       value=\"deny\"/>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <!-- /content -->\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- /content/body -->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- footer -->\n");
      out.write("<footer class=\"footer\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <p>WSO2 Identity Server | &copy; <script>document.write(new Date().getFullYear());</script> <a href=\"http://wso2.com/\" target=\"_blank\"><i class=\"icon fw fw-wso2\"></i> Inc</a>. All Rights Reserved.</p>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"libs/jquery_1.11.3/jquery-1.11.3.js\"></script>\n");
      out.write("<script src=\"libs/bootstrap_3.3.5/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
